version: '3'
services:
  signal-api:  
    image: bbernhard/signal-cli-rest-api:latest
    restart: unless-stopped
    container_name: signal_api
    environment:
      - USE_NATIVE=0
      - AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "/opt/docker/cfg/signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
